# Generated by Django 5.0.4 on 2026-03-22 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('handwritten_notes', 'Handwritten Notes'), ('study_material', 'Study Material'), ('previous_question_paper', 'Previous Question Paper'), ('video', 'Video')], default='study_material', max_length=40),
        ),
        migrations.CreateModel(
            name='VideoWatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('progress_seconds', models.PositiveIntegerField(default=0)),
                ('watched_at', models.DateTimeField(blank=True, null=True)),
                ('last_interaction_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_statuses', to='core.material')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_watch_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('material', 'student')},
            },
        ),
    ]
