# Generated by Django 4.2.20 on 2026-03-24 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_material_material_type_videowatchstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentAcademicProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(blank=True, max_length=150)),
                ("roll_number", models.CharField(blank=True, max_length=50)),
                ("division", models.CharField(blank=True, max_length=30)),
                ("batch", models.CharField(blank=True, max_length=50)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("semester", models.CharField(blank=True, max_length=30)),
                ("internship", models.BooleanField(default=False)),
                ("internship_company", models.CharField(blank=True, max_length=150)),
                ("internship_domain", models.CharField(blank=True, max_length=150)),
                ("marks", models.FloatField(default=0.0)),
                ("attendance_percentage", models.FloatField(default=0.0)),
                ("quiz_average", models.FloatField(default=0.0)),
                ("assignment_average", models.FloatField(default=0.0)),
                ("skills", models.TextField(blank=True)),
                ("strengths", models.TextField(blank=True)),
                ("improvement_areas", models.TextField(blank=True)),
                ("career_goal", models.CharField(blank=True, max_length=200)),
                ("guardian_name", models.CharField(blank=True, max_length=150)),
                ("guardian_contact", models.CharField(blank=True, max_length=20)),
                (
                    "predicted_band",
                    models.CharField(
                        blank=True, default="Not generated", max_length=50
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(blank=True, default="Unknown", max_length=50),
                ),
                ("ai_suggestions", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_academic_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
